openapi: 3.0.0
info:
  title: {{title}}
  description: {{description}}
  contact:
    name: {{contact_name}}
    email: {{contact_email}}
    url:  {{contact_website}}
  version: {{version}}

servers:
  - url: /


security:
  - basicAuth: []


tags:
  - name: Health


paths:
  /ping:
    get:
      summary: Check the API health
      security: []
      tags:
        - Health
      operationId: wine_predictor_api.services.healthcheck.ping
      responses:
        '200':
          description: API is up and running
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      x-basicInfoFunc: wine_predictor_api.security.authentication.basic_auth